name: Update EPG Files

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (UTC)
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-epgs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download the EPG files securely
        env:
          URL_1: ${{ secrets.EPG_URL_1 }}
          URL_2: ${{ secrets.EPG_URL_2 }}
          FILE_1: ${{ secrets.EPG_FILE_1 }}
          FILE_2: ${{ secrets.EPG_FILE_2 }}
        run: |
          curl -L "$URL_1" -o "$FILE_1"
          curl -L "$URL_2" -o "$FILE_2"

      - name: Merge EPG files
        env:
          FILE_1: ${{ secrets.EPG_FILE_1 }}
          FILE_2: ${{ secrets.EPG_FILE_2 }}
        run: |
          gzip -d -c "$FILE_1" > decompressed1.xml
          gzip -d -c "$FILE_2" > decompressed2.xml
          
          echo '<?xml version="1.0" encoding="UTF-8"?>' > strong.xml
          echo '<tv generator-info-name="Strong EPG" generator-info-url="https://github.com/SubTek/EPG">' >> strong.xml
          
          sed '1d;$d' decompressed1.xml >> strong.xml
          sed '1d;$d' decompressed2.xml >> strong.xml
          
          echo '</tv>' >> strong.xml
          
          gzip -k strong.xml

      - name: Commit and push changes if any
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git add strong.xml strong.xml.gz
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update EPG files"
            git push origin main
          else
            echo "No changes detected, nothing to commit."
          fi
