name: Update EPG Files

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (UTC)
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-epgs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download the EPG files
        env:
          URL_1: ${{ secrets.EPG_URL_1 }}
          URL_2: ${{ secrets.EPG_URL_2 }}
          FILE_1: ${{ secrets.EPG_FILE_1 }}
          FILE_2: ${{ secrets.EPG_FILE_2 }}
        run: |
          curl -L "$URL_1" -o "$FILE_1"
          curl -L "$URL_2" -o "$FILE_2"

      - name: Commit and push changes if any
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          if [ -n "$(git status --porcelain)" ]; then
            git add "$FILE_1" "$FILE_2"
            git commit -m "Update multiple EPG files"
            git push origin main
          else
            echo "No changes detected, nothing to commit."
